Invert conditional

diff --git a/compile-project b/compile-project
--- a/compile-project
+++ b/compile-project
@@ -73,7 +73,10 @@ compile_in_directory() {
 compile_in_directory "$toplevel"
 result=$?
 
-if [ "$result" = 222 ] ; then
+if [ "$result" != 222 ] ; then
+  # A buildfile was found, exit with the exit code of the compilation step.
+  exit $result
+else
   buildfile_found=0
   for subdir in "$toplevel"/*/ ; do
     compile_in_directory "$subdir"
@@ -89,7 +92,4 @@ if [ "$result" = 222 ] ; then
   if [ "$buildfile_found" = 0 ] && [ -n "$ERR_IF_NO_BUILDFILE" ]; then
     exit 1
   fi
-else
-  # A buildfile was found, exit with the exit code of the compilation step.
-  exit $result
 fi
