Status code when a top-level buildfile exists

diff --git a/compile-project b/compile-project
--- a/compile-project
+++ b/compile-project
@@ -73,7 +73,11 @@ compile_in_directory() {
 compile_in_directory "$toplevel"
 result=$?
 
-if [ "$result" = 222 ] ; then
+if [ "$result" != 222 ] ; then
+  # A buildfile was found, exit with the exit code of the compilation step.
+  exit $result
+else
+  # Call compile_in_directory in subdirectories.
   buildfile_found=0
   for subdir in "$toplevel"/*/ ; do
     compile_in_directory "$subdir"
