Reformat

diff --git a/git-checkout-branch b/git-checkout-branch
--- a/git-checkout-branch
+++ b/git-checkout-branch
@@ -11,10 +11,10 @@ if [ "$#" -ne 1 ]; then
   exit 1
 fi
 
-if ! cd "$(git rev-parse --show-toplevel 2>&1)" ; then
-    echo "$(basename "$0"): Cannot determine top-level directory of git repository"
-    git rev-parse --show-toplevel
-    return 1
+if ! cd "$(git rev-parse --show-toplevel 2>&1)"; then
+  echo "$(basename "$0"): Cannot determine top-level directory of git repository"
+  git rev-parse --show-toplevel
+  return 1
 fi
 
 REPO=$(basename "$(pwd)")
@@ -22,33 +22,33 @@ BRANCHNAME="$1"
 BRANCHNOSLASH=$(echo "${BRANCHNAME}" | sed -e "s:/:-:g")
 BRANCHDIR=$(realpath "../${REPO%%-branch-*}-branch-${BRANCHNOSLASH}")
 
-git pull -q > /dev/null 2>&1 || true
+git pull -q >/dev/null 2>&1 || true
 
-if [ -z "$(git branch -r --list "origin/${BRANCHNAME}")" ] ; then
-    if ! git ls-remote --exit-code origin "${BRANCHNAME}" ; then
-	echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} does not exist."
-	exit 1
-    fi
+if [ -z "$(git branch -r --list "origin/${BRANCHNAME}")" ]; then
+  if ! git ls-remote --exit-code origin "${BRANCHNAME}"; then
+    echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} does not exist."
+    exit 1
+  fi
 fi
 
-if [ -e "${BRANCHDIR}" ] ; then
+if [ -e "${BRANCHDIR}" ]; then
   echo "$(basename "$0"): ERROR: directory exists: ${BRANCHDIR}"
   exit 1
 fi
 
-if ! \cp -Rp . "${BRANCHDIR}" ; then
-    echo "$(basename "$0"): ERROR: cannot copy $(pwd) to ${BRANCHDIR}"
-    exit 1
+if ! \cp -Rp . "${BRANCHDIR}"; then
+  echo "$(basename "$0"): ERROR: cannot copy $(pwd) to ${BRANCHDIR}"
+  exit 1
 fi
-if ! cd "${BRANCHDIR}" ; then
-    echo "$(basename "$0"): ERROR in: cd \"${BRANCHDIR}\""
-    exit 1
+if ! cd "${BRANCHDIR}"; then
+  echo "$(basename "$0"): ERROR in: cd \"${BRANCHDIR}\""
+  exit 1
 fi
-if ! git checkout "${BRANCHNAME}" -- ; then
-    echo "$(basename "$0"): ERROR in: git checkout \"${BRANCHNAME}\" --"
-    exit 1
+if ! git checkout "${BRANCHNAME}" --; then
+  echo "$(basename "$0"): ERROR in: git checkout \"${BRANCHNAME}\" --"
+  exit 1
 fi
 
-git pull -q > /dev/null 2>&1 || true
+git pull -q >/dev/null 2>&1 || true
 
 echo "Success: checked out to ${BRANCHDIR}"
diff --git a/git-new-branch b/git-new-branch
--- a/git-new-branch
+++ b/git-new-branch
@@ -11,10 +11,10 @@ if [ "$#" -ne 1 ]; then
   exit 1
 fi
 
-if ! cd "$(git rev-parse --show-toplevel 2>&1)" ; then
-    echo "$(basename "$0"): Cannot determine top-level directory of git repository"
-    git rev-parse --show-toplevel
-    return 1
+if ! cd "$(git rev-parse --show-toplevel 2>&1)"; then
+  echo "$(basename "$0"): Cannot determine top-level directory of git repository"
+  git rev-parse --show-toplevel
+  return 1
 fi
 
 REPO=$(basename "$(pwd)")
@@ -23,43 +23,43 @@ BRANCHNOSLASH=$(echo "${BRANCHNAME}" | sed -e "s:/:-:g")
 BRANCHDIR=$(realpath "../${REPO%%-branch-*}-branch-${BRANCHNOSLASH}")
 TMPDIR="${BRANCHDIR}-TMP"
 
-git pull -q > /dev/null 2>&1 || true
+git pull -q >/dev/null 2>&1 || true
 
-if [ -n "$(git branch -r --list "origin/${BRANCHNAME}")" ] ; then
+if [ -n "$(git branch -r --list "origin/${BRANCHNAME}")" ]; then
+  echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} already exists."
+  exit 1
+else
+  if git ls-remote --exit-code origin "${BRANCHNAME}"; then
     echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} already exists."
     exit 1
-else
-    if git ls-remote --exit-code origin "${BRANCHNAME}" ; then
-	echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} already exists."
-	exit 1
-    fi
+  fi
 fi
 
-if [ -e "${BRANCHDIR}" ] ; then
+if [ -e "${BRANCHDIR}" ]; then
   echo "$(basename "$0"): ERROR: directory exists: ${BRANCHDIR}"
   exit 1
 fi
-if [ -e "${TMPDIR}" ] ; then
+if [ -e "${TMPDIR}" ]; then
   echo "$(basename "$0"): ERROR: directory exists: ${TMPDIR}"
   exit 1
 fi
 
-if ! \cp -Rp . "${TMPDIR}" ; then
-    echo "$(basename "$0"): ERROR: cannot copy $(pwd) to ${TMPDIR}"
-    exit 1
+if ! \cp -Rp . "${TMPDIR}"; then
+  echo "$(basename "$0"): ERROR: cannot copy $(pwd) to ${TMPDIR}"
+  exit 1
 fi
-if ! (cd "${TMPDIR}" && git checkout -b "${BRANCHNAME}" -q) ; then
-    echo "$(basename "$0"): ERROR in: (cd \"${TMPDIR}\" && git checkout -b \"${BRANCHNAME}\" -q)"
-    exit 1
+if ! (cd "${TMPDIR}" && git checkout -b "${BRANCHNAME}" -q); then
+  echo "$(basename "$0"): ERROR in: (cd \"${TMPDIR}\" && git checkout -b \"${BRANCHNAME}\" -q)"
+  exit 1
 fi
-if ! mv "${TMPDIR}" "${BRANCHDIR}" ; then
-    echo "$(basename "$0"): ERROR in: mv \"${TMPDIR}\" \"${BRANCHDIR}\""
-    exit 1
+if ! mv "${TMPDIR}" "${BRANCHDIR}"; then
+  echo "$(basename "$0"): ERROR in: mv \"${TMPDIR}\" \"${BRANCHDIR}\""
+  exit 1
 fi
 
-if ! cd "${BRANCHDIR}" ; then
-    echo "$(basename "$0"): ERROR in: cd \"${BRANCHDIR}\""
-    exit 1
+if ! cd "${BRANCHDIR}"; then
+  echo "$(basename "$0"): ERROR in: cd \"${BRANCHDIR}\""
+  exit 1
 fi
 
 echo "Success: created ${BRANCHDIR}"
diff --git a/git-push-to b/git-push-to
--- a/git-push-to
+++ b/git-push-to
@@ -79,76 +79,74 @@
 #     MYDIR/myrepo-branch-part2 \
 #     MYDIR/myrepo-branch-allchanges
 
-
 nocompile=0
 
-
 ## A helper function that works on exactly two repositories.
-git_push_to () {
+git_push_to() {
 
-from="$1"
-from_absolute="$(realpath "$from")"
-to="$2"
-to_absolute="$(realpath "$to")"
+  from="$1"
+  from_absolute="$(realpath "$from")"
+  to="$2"
+  to_absolute="$(realpath "$to")"
 
-if [ ! -d "${from}" ]; then
-  if [ "${from}" = "${from_absolute}" ] ; then
-    echo "$(basename "$0"): no such directory: $from"
-  else
-    echo "$(basename "$0"): no such directory: ${from} = ${from_absolute}"
-  fi  
-  return 1
-fi
-if [ ! -d "$to" ]; then
-  if [ "${to}" = "${to_absolute}" ] ; then
-    echo "$(basename "$0"): no such directory: $to"
-  else
-    echo "$(basename "$0"): no such directory: ${to} = ${to_absolute}"
-  fi  
-  return 1
-fi
-
-if ! git -C "$from_absolute" pull -q ; then
-  echo "$(basename "$0"): problem pulling ${from_absolute}"
-  return 1
-fi
-
-orig_dir=$(pwd)
-
-if ! cd "$to_absolute" ; then
-  echo "$(basename "$0"): cannot cd to ${to_absolute}"
-  return 1
-fi
-
-if ! git pull -q ; then
-  echo "$(basename "$0"): problem pulling in ${to_absolute}"
-  return 1
-fi
-
-from_relative="$(realpath --relative-to="$to_absolute" "$from_absolute")"
-
-if ! git pull -q "${from_relative}" ; then
-  # Note: pwd=to_absolute
-  echo "$(basename "$0"): problem pulling ${from_absolute} into $(pwd)"
-  return 1
-fi
-
-if [ "$nocompile" -eq 0 ] && [ -z "$MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT" ] ; then
-  if ! compile-project ; then
-    echo "$(basename "$0"): unable to build in $(pwd)"
+  if [ ! -d "${from}" ]; then
+    if [ "${from}" = "${from_absolute}" ]; then
+      echo "$(basename "$0"): no such directory: $from"
+    else
+      echo "$(basename "$0"): no such directory: ${from} = ${from_absolute}"
+    fi
     return 1
   fi
-fi
+  if [ ! -d "$to" ]; then
+    if [ "${to}" = "${to_absolute}" ]; then
+      echo "$(basename "$0"): no such directory: $to"
+    else
+      echo "$(basename "$0"): no such directory: ${to} = ${to_absolute}"
+    fi
+    return 1
+  fi
 
-if ! git push --quiet; then
-  echo "$(basename "$0"): problem pushing from $(pwd)"
-  return 1
-fi
+  if ! git -C "$from_absolute" pull -q; then
+    echo "$(basename "$0"): problem pulling ${from_absolute}"
+    return 1
+  fi
 
-if ! cd "${orig_dir}" ; then
-  echo "$(basename "$0"): cannot cd back to ${orig_dir}"
-  return 1
-fi
+  orig_dir=$(pwd)
+
+  if ! cd "$to_absolute"; then
+    echo "$(basename "$0"): cannot cd to ${to_absolute}"
+    return 1
+  fi
+
+  if ! git pull -q; then
+    echo "$(basename "$0"): problem pulling in ${to_absolute}"
+    return 1
+  fi
+
+  from_relative="$(realpath --relative-to="$to_absolute" "$from_absolute")"
+
+  if ! git pull -q "${from_relative}"; then
+    # Note: pwd=to_absolute
+    echo "$(basename "$0"): problem pulling ${from_absolute} into $(pwd)"
+    return 1
+  fi
+
+  if [ "$nocompile" -eq 0 ] && [ -z "$MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT" ]; then
+    if ! compile-project; then
+      echo "$(basename "$0"): unable to build in $(pwd)"
+      return 1
+    fi
+  fi
+
+  if ! git push --quiet; then
+    echo "$(basename "$0"): problem pushing from $(pwd)"
+    return 1
+  fi
+
+  if ! cd "${orig_dir}"; then
+    echo "$(basename "$0"): cannot cd back to ${orig_dir}"
+    return 1
+  fi
 
 }
 
@@ -165,8 +163,8 @@ if [ "$#" -lt 2 ]; then
 fi
 
 for arg; do
-  if [ -n "$prev" ] ; then
-    if ! git_push_to "$prev" "$arg" ; then
+  if [ -n "$prev" ]; then
+    if ! git_push_to "$prev" "$arg"; then
       exit 1
     fi
   fi
