Respect environment variable MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT

diff --git a/git-pull-from b/git-pull-from
--- a/git-pull-from
+++ b/git-pull-from
@@ -1,7 +1,9 @@
 #!/bin/sh
 
 # Pull from another directory into the current repository.  Fails if
-# the resulting merge does not compile.
+# the resulting merge does not compile.  (Skips the compilation step
+# if environment variable MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT is
+# set.)
 # 
 # Usage:
 #   git-pull-from OTHER-REPO-DIR
@@ -51,9 +53,11 @@ if ! git pull -q "${from_absolute}"; then
   exit 1
 fi
 
-if ! compile-project ; then
-  echo "$(basename "$0"): unable to build in $(pwd)"
-  exit 1
+if [ -z "${MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT}" ] ; then
+  if ! compile-project ; then
+    echo "$(basename "$0"): unable to build in $(pwd)"
+    exit 1
+  fi
 fi
 
 if ! git push; then
diff --git a/git-push-to b/git-push-to
--- a/git-push-to
+++ b/git-push-to
@@ -14,6 +14,8 @@
 #  * pull FROM_DIR and TO_DIR from their remotes,
 #  * pull FROM_DIR into TO_DIR,
 #  * build TO_DIR using `compile-project` (see its documentation),
+#    (Skips the compilation step if environment variable
+#    MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT is set.)
 #  * push TO_DIR to its remote if the build succeeds.
 #
 # If more than two directories are supplied, the procedure is performed on each
@@ -124,9 +126,11 @@ if ! git pull -q "${from_absolute}" ; then
   return 1
 fi
 
-if ! compile-project ; then
-  echo "$(basename "$0"): unable to build in $(pwd)"
-  return 1
+if [ -z "$MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT" ] ; then
+  if ! compile-project ; then
+    echo "$(basename "$0"): unable to build in $(pwd)"
+    return 1
+  fi
 fi
 
 if ! git push; then
