Briefer usage messages

diff --git a/git-checkout-branch b/git-checkout-branch
--- a/git-checkout-branch
+++ b/git-checkout-branch
@@ -7,12 +7,12 @@
 #   git-checkout-branch BRANCHNAME
 
 if [ "$#" -ne 1 ]; then
-  echo "Usage: $0 BRANCHNAME" >&2
+  echo "Usage: $(basename "$0") BRANCHNAME" >&2
   exit 1
 fi
 
 if ! cd "$(git rev-parse --show-toplevel)" ; then
-    echo "$0: Cannot determine top-level directory of git repository"
+    echo "$(basename "$0"): Cannot determine top-level directory of git repository"
     git rev-parse --show-toplevel
     return 1
 fi
@@ -26,26 +26,26 @@ git pull -q > /dev/null 2>&1 || true
 
 if [ -z "$(git branch -r --list "origin/${BRANCHNAME}")" ] ; then
     if ! git ls-remote --exit-code origin "${BRANCHNAME}" ; then
-	echo "$0: ERROR: branch ${BRANCHNAME} does not exist."
+	echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} does not exist."
 	return 1
     fi
 fi
 
 if [ -e "${BRANCHDIR}" ] ; then
-  echo "$0: ERROR: directory exists: ${BRANCHDIR}"
+  echo "$(basename "$0"): ERROR: directory exists: ${BRANCHDIR}"
   exit 1
 fi
 
 if ! \cp -Rp . "${BRANCHDIR}" ; then
-    echo "$0: ERROR: cannot copy $(pwd) to ${BRANCHDIR}"
+    echo "$(basename "$0"): ERROR: cannot copy $(pwd) to ${BRANCHDIR}"
     return 1
 fi
 if ! cd "${BRANCHDIR}" ; then
-    echo "$0: ERROR in: cd \"${BRANCHDIR}\""
+    echo "$(basename "$0"): ERROR in: cd \"${BRANCHDIR}\""
     return 1
 fi
 if ! git checkout "${BRANCHNAME}" -- ; then
-    echo "$0: ERROR in: git checkout \"${BRANCHNAME}\" --"
+    echo "$(basename "$0"): ERROR in: git checkout \"${BRANCHNAME}\" --"
     return 1
 fi
 
diff --git a/git-new-branch b/git-new-branch
--- a/git-new-branch
+++ b/git-new-branch
@@ -7,12 +7,12 @@
 #   git-new-branch NEWBRANCHNAME
 
 if [ "$#" -ne 1 ]; then
-  echo "Usage: $0 NEWBRANCHNAME" >&2
+  echo "Usage: $(basename "$0") NEWBRANCHNAME" >&2
   exit 1
 fi
 
 if ! cd "$(git rev-parse --show-toplevel)" ; then
-    echo "$0: Cannot determine top-level directory of git repository"
+    echo "$(basename "$0"): Cannot determine top-level directory of git repository"
     git rev-parse --show-toplevel
     return 1
 fi
@@ -26,39 +26,39 @@ TMPDIR="${BRANCHDIR}-TMP"
 git pull -q > /dev/null 2>&1 || true
 
 if [ -n "$(git branch -r --list "origin/${BRANCHNAME}")" ] ; then
-    echo "$0: ERROR: branch ${BRANCHNAME} already exists."
+    echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} already exists."
     return 1
 else
     if git ls-remote --exit-code origin "${BRANCHNAME}" ; then
-	echo "$0: ERROR: branch ${BRANCHNAME} already exists."
+	echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} already exists."
 	return 1
     fi
 fi
 
 if [ -e "${BRANCHDIR}" ] ; then
-  echo "$0: ERROR: directory exists: ${BRANCHDIR}"
+  echo "$(basename "$0"): ERROR: directory exists: ${BRANCHDIR}"
   exit 1
 fi
 if [ -e "${TMPDIR}" ] ; then
-  echo "$0: ERROR: directory exists: ${TMPDIR}"
+  echo "$(basename "$0"): ERROR: directory exists: ${TMPDIR}"
   exit 1
 fi
 
 if ! \cp -Rp . "${TMPDIR}" ; then
-    echo "$0: ERROR: cannot copy $(pwd) to ${TMPDIR}"
+    echo "$(basename "$0"): ERROR: cannot copy $(pwd) to ${TMPDIR}"
     return 1
 fi
 if ! (cd "${TMPDIR}" && git checkout -b "${BRANCHNAME}" -q) ; then
-    echo "$0: ERROR in: (cd \"${TMPDIR}\" && git checkout -b \"${BRANCHNAME}\" -q)"
+    echo "$(basename "$0"): ERROR in: (cd \"${TMPDIR}\" && git checkout -b \"${BRANCHNAME}\" -q)"
     return 1
 fi
 if ! mv "${TMPDIR}" "${BRANCHDIR}" ; then
-    echo "$0: ERROR in: mv \"${TMPDIR}\" \"${BRANCHDIR}\""
+    echo "$(basename "$0"): ERROR in: mv \"${TMPDIR}\" \"${BRANCHDIR}\""
     return 1
 fi
 
 if ! cd "${BRANCHDIR}" ; then
-    echo "$0: ERROR in: cd \"${BRANCHDIR}\""
+    echo "$(basename "$0"): ERROR in: cd \"${BRANCHDIR}\""
     return 1
 fi
 
diff --git a/git-pull-from b/git-pull-from
--- a/git-pull-from
+++ b/git-pull-from
@@ -19,7 +19,7 @@
 
 
 if [ "$#" -ne 1 ]; then
-  echo "Usage: $0 OTHER-REPO-DIR" >&2
+  echo "Usage: $(basename "$0") OTHER-REPO-DIR" >&2
   exit 1
 fi
 
@@ -29,34 +29,34 @@ from_absolute="$(realpath --relative-to="." "$from")"
 
 if [ ! -d "${from}" ]; then
   if [ "${from}" = "${from_absolute}" ] ; then
-    echo "$0: no such directory: $from"
+    echo "$(basename "$0"): no such directory: $from"
   else
-    echo "$0: no such directory: ${from} = ${from_absolute}"
+    echo "$(basename "$0"): no such directory: ${from} = ${from_absolute}"
   fi  
   exit 1
 fi
 
 if ! git pull -q; then
-  echo "$0: problem pulling $(pwd)"
+  echo "$(basename "$0"): problem pulling $(pwd)"
   exit 1
 fi
 
 if ! git -C "$from" pull -q ; then
-  echo "$0: problem pulling ${from}"
+  echo "$(basename "$0"): problem pulling ${from}"
   exit 1
 fi
 
 if ! git pull -q "${from_absolute}"; then
-  echo "$0: problem pulling ${from_absolute} into $(pwd)"
+  echo "$(basename "$0"): problem pulling ${from_absolute} into $(pwd)"
   exit 1
 fi
 
 if ! compile-project ; then
-  echo "$0: unable to build in $(pwd)"
+  echo "$(basename "$0"): unable to build in $(pwd)"
   exit 1
 fi
 
 if ! git push; then
-  echo "$0: problem pushing from $(pwd)"
+  echo "$(basename "$0"): problem pushing from $(pwd)"
   exit 1
 fi
diff --git a/git-push-to b/git-push-to
--- a/git-push-to
+++ b/git-push-to
@@ -74,55 +74,55 @@ to_absolute="$(realpath "$to")"
 
 if [ ! -d "${from}" ]; then
   if [ "${from}" = "${from_absolute}" ] ; then
-    echo "$0: no such directory: $from"
+    echo "$(basename "$0"): no such directory: $from"
   else
-    echo "$0: no such directory: ${from} = ${from_absolute}"
+    echo "$(basename "$0"): no such directory: ${from} = ${from_absolute}"
   fi  
   return 1
 fi
 if [ ! -d "$to" ]; then
   if [ "${to}" = "${to_absolute}" ] ; then
-    echo "$0: no such directory: $to"
+    echo "$(basename "$0"): no such directory: $to"
   else
-    echo "$0: no such directory: ${to} = ${to_absolute}"
+    echo "$(basename "$0"): no such directory: ${to} = ${to_absolute}"
   fi  
   return 1
 fi
 
 if ! git -C "$from_absolute" pull -q ; then
-  echo "$0: problem pulling ${from_absolute}"
+  echo "$(basename "$0"): problem pulling ${from_absolute}"
   return 1
 fi
 
 orig_dir=$(pwd)
 
 if ! cd "$to_absolute" ; then
-  echo "$0: cannot cd to ${to_absolute}"
+  echo "$(basename "$0"): cannot cd to ${to_absolute}"
   return 1
 fi
 
 if ! git pull -q ; then
-  echo "$0: problem pulling in ${to_absolute}"
+  echo "$(basename "$0"): problem pulling in ${to_absolute}"
   return 1
 fi
 
 if ! git pull -q "${from_absolute}" ; then
-  echo "$0: problem pulling ${from_absolute} into $(pwd)"
+  echo "$(basename "$0"): problem pulling ${from_absolute} into $(pwd)"
   return 1
 fi
 
 if ! compile-project ; then
-  echo "$0: unable to build in $(pwd)"
+  echo "$(basename "$0"): unable to build in $(pwd)"
   return 1
 fi
 
 if ! git push; then
-  echo "$0: problem pushing from $(pwd)"
+  echo "$(basename "$0"): problem pushing from $(pwd)"
   return 1
 fi
 
 if ! cd "${orig_dir}" ; then
-  echo "$0: cannot cd back to ${orig_dir}"
+  echo "$(basename "$0"): cannot cd back to ${orig_dir}"
   return 1
 fi
 
@@ -131,7 +131,7 @@ fi
 ## Main program starts here.
 
 if [ "$#" -lt 2 ]; then
-  echo "Usage: $0 FROM_DIR TO_DIR ..." >&2
+  echo "Usage: $(basename "$0") FROM_DIR TO_DIR ..." >&2
   exit 1
 fi
 
