Use variable for script name

diff --git a/git-checkout-branch b/git-checkout-branch
--- a/git-checkout-branch
+++ b/git-checkout-branch
@@ -6,15 +6,18 @@
 # Usage:
 #   git-checkout-branch BRANCHNAME
 
+# SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
+SCRIPT_NAME="$(basename -- "$0")"
+
 if [ "$#" -ne 1 ]; then
-  echo "Usage: $(basename "$0") BRANCHNAME" >&2
+  echo "Usage: ${SCRIPT_NAME} BRANCHNAME" >&2
   exit 1
 fi
 
 STARTDIR="${PWD}"
 
 if ! cd "$(git rev-parse --show-toplevel 2>&1)"; then
-  echo "$(basename "$0"): Cannot determine top-level directory of git repository"
+  echo "${SCRIPT_NAME}: Cannot determine top-level directory of git repository"
   git rev-parse --show-toplevel
   cd "${STARTDIR}" || exit 1
   exit 1
@@ -30,30 +33,30 @@ git pull -q > /dev/null 2>&1 || true
 
 if [ -z "$(git branch -r --list "origin/${BRANCHNAME}")" ]; then
   if ! git ls-remote --exit-code origin "${BRANCHNAME}"; then
-    echo "$(basename "$0"): ERROR: branch ${BRANCHNAME} does not exist."
+    echo "${SCRIPT_NAME}: ERROR: branch ${BRANCHNAME} does not exist."
     cd "${STARTDIR}" || exit 1
     exit 1
   fi
 fi
 
 if [ -e "${BRANCHDIR}" ]; then
-  echo "$(basename "$0"): ERROR: directory exists: ${BRANCHDIR}"
+  echo "${SCRIPT_NAME}: ERROR: directory exists: ${BRANCHDIR}"
   cd "${STARTDIR}" || exit 1
   exit 1
 fi
 if [ -e "${TMPDIR}" ]; then
-  echo "$(basename "$0"): ERROR: directory exists: ${TMPDIR}"
+  echo "${SCRIPT_NAME}: ERROR: directory exists: ${TMPDIR}"
   cd "${STARTDIR}" || exit 1
   exit 1
 fi
 
 if ! \cp -Rp . "${TMPDIR}"; then
-  echo "$(basename "$0"): ERROR: cannot copy $(pwd) to ${TMPDIR}"
+  echo "${SCRIPT_NAME}: ERROR: cannot copy $(pwd) to ${TMPDIR}"
   cd "${STARTDIR}" || exit 1
   exit 1
 fi
 if ! (cd "${TMPDIR}" && git checkout "${BRANCHNAME}" -q); then
-  echo "$(basename "$0"): ERROR in: (cd \"${TMPDIR}\" && git checkout \"${BRANCHNAME}\" -q)"
+  echo "${SCRIPT_NAME}: ERROR in: (cd \"${TMPDIR}\" && git checkout \"${BRANCHNAME}\" -q)"
   cd "${STARTDIR}" || exit 1
   exit 1
 fi
@@ -61,7 +64,7 @@ fi
 git pull -q > /dev/null 2>&1 || true
 
 if ! mv "${TMPDIR}" "${BRANCHDIR}"; then
-  echo "$(basename "$0"): ERROR in: mv \"${TMPDIR}\" \"${BRANCHDIR}\""
+  echo "${SCRIPT_NAME}: ERROR in: mv \"${TMPDIR}\" \"${BRANCHDIR}\""
   cd "${STARTDIR}" || exit 1
   exit 1
 fi
diff --git a/git-pull-from b/git-pull-from
--- a/git-pull-from
+++ b/git-pull-from
@@ -19,8 +19,11 @@
 #
 # Calling `git-push-to` is often more readable, because it makes both directory names explicit.
 
+# SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
+SCRIPT_NAME="$(basename -- "$0")"
+
 if [ "$#" -ne 1 ]; then
-  echo "Usage: $(basename "$0") OTHER-REPO-DIR" >&2
+  echo "Usage: ${SCRIPT_NAME} OTHER-REPO-DIR" >&2
   exit 1
 fi
 
@@ -29,36 +32,36 @@ from_absolute="$(realpath --relative-to="." "$from")"
 
 if [ ! -d "${from}" ]; then
   if [ "${from}" = "${from_absolute}" ]; then
-    echo "$(basename "$0"): no such directory: $from"
+    echo "${SCRIPT_NAME}: no such directory: $from"
   else
-    echo "$(basename "$0"): no such directory: ${from} = ${from_absolute}"
+    echo "${SCRIPT_NAME}: no such directory: ${from} = ${from_absolute}"
   fi
   exit 1
 fi
 
 if ! git pull -q; then
-  echo "$(basename "$0"): problem pulling $(pwd)"
+  echo "${SCRIPT_NAME}: problem pulling $(pwd)"
   exit 1
 fi
 
 if ! git -C "$from" pull -q; then
-  echo "$(basename "$0"): problem pulling ${from}"
+  echo "${SCRIPT_NAME}: problem pulling ${from}"
   exit 1
 fi
 
 if ! git pull -q "${from_absolute}"; then
-  echo "$(basename "$0"): problem pulling ${from_absolute} into $(pwd)"
+  echo "${SCRIPT_NAME}: problem pulling ${from_absolute} into $(pwd)"
   exit 1
 fi
 
 if [ -z "${MANAGE_GIT_BRANCHES_SKIP_COMPILE_PROJECT}" ]; then
   if ! compile-project; then
-    echo "$(basename "$0"): unable to build in $(pwd)"
+    echo "${SCRIPT_NAME}: unable to build in $(pwd)"
     exit 1
   fi
 fi
 
 if ! git push; then
-  echo "$(basename "$0"): problem pushing from $(pwd)"
+  echo "${SCRIPT_NAME}: problem pushing from $(pwd)"
   exit 1
 fi
